LMS-005: Adding migrarion,seeder and factory for authorm,category,publisher
Mitali-Gautam/laravelproject pull request #4
Opened 2023-08-19 08:27 UTC by Mitali-Gautam

This branch is about adding migrations and seeders for authors,publishers and categories

Command : 
php artisan migrate
php artisan db:seed

2023-08-24 04:08 UTC, mehulprajapatii requested changes

2023-08-24 04:08 UTC, mehulprajapatii commented on database/factories/AuthorFactory.php
> +            "updated_at"=>$this->faker->dateTime()
Use PSR 4 ,
            'updated_at' => $this->faker->dateTime(),

2023-08-24 04:08 UTC, mehulprajapatii commented on database/factories/AuthorFactory.php
> +            "name"=>$this->faker->name,
Use single quote

2023-08-24 04:08 UTC, mehulprajapatii commented on database/factories/CategoryFactory.php
> +            "name"=>$this->faker->name,
use single quote and PSR 4 coding standard

2023-08-24 04:08 UTC, mehulprajapatii commented on database/factories/StudentFactory.php
> +                "updated_at"=>$this->faker->dateTime()
Add , after last array element

2023-08-24 04:08 UTC, mehulprajapatii commented on database/migrations/2023_08_19_075102_create_publishers_table.php
> +            $table->string("name",100);
space after comma e.g. 'name', 100

2023-08-24 04:08 UTC, mehulprajapatii commented on database/migrations/2023_08_19_075102_create_publishers_table.php
> +            $table->enum("is_deleted",[1,0])->default(0);
Add ->comment('usage of column'); for description of column

2023-08-24 04:08 UTC, mehulprajapatii commented on database/seeders/DatabaseSeeder.php
> -        //     'name' => 'Test User',
remove commented code

2023-09-01 05:23 UTC, mehulprajapatii approved these changes

2023-09-02 13:57 UTC, Mitali-Gautam commented on database/factories/AuthorFactory.php
> +            "name"=>$this->faker->name,
Done

2023-09-02 13:58 UTC, Mitali-Gautam commented on database/factories/StudentFactory.php
> +                "updated_at"=>$this->faker->dateTime()
Done

2023-09-02 13:58 UTC, Mitali-Gautam commented on database/migrations/2023_08_19_075102_create_publishers_table.php
> +            $table->string("name",100);
Done

2023-09-02 13:58 UTC, Mitali-Gautam commented on database/seeders/DatabaseSeeder.php
> -        //     'name' => 'Test User',
Done

2023-09-04 05:27 UTC, mehulprajapatii approved these changes

2023-09-06 07:41 UTC, merged